### ISSUE TITLE
Better highlighting of core apps

### ISSUE THREAD

**Issue by OriginalFannibal** [Kazhnuz/awesome-gnome#16]
Currently, we identify core apps at the end of the description of the item. I suggest doing something along the lines of what [Awesome macOS](https://github.com/iCHAIT/awesome-macOS) does to highlight free apps and open source apps. 

That project uses small images at the end of the description to highlight the item as either free or as open source. We could use a small image of the GNOME project logo for the same and explain this at the start of the document.

**Comment by Kazhnuz** [comment]
Done in eafb4519628d4ba55933ece1b535e7261d497e91

**Comment by OriginalFannibal** [comment]
That looks gorgeous!
