### ISSUE TITLE
Moving apps without a stable release to the issue tracker

### ISSUE THREAD

**Issue by OriginalFannibal** [Kazhnuz/awesome-gnome#17]
I noticed that we currently have Lutris in the issue tracker as it doesn't yet fit our requirements but might someday. I suggest doing the same with apps which do not have a single stable release yet. This way the quality of the list would be higher. This is an awesome list after all so should it have unstable apps in it? 

Since we do have them in the issue tracker, we can revisit them once they release a stable version and add them into the actual list. Right now, this would mean moving Dino to the issue tracker. In the future, we should add something regarding this in the contribution guidelines or anywhere else that will make it clear that unstable apps can only be added to the issue tracker and not to the main list until they have a stable release.

**Comment by Kazhnuz** [comment]
Yes, you're right. Maybe we should add then some kind of label for the issue tracker for the application that would be great in the list once they are stable ? But I'm not sure of what would be the best way to label them… ("unstable" or "future addition", maybe ?)

**Comment by OriginalFannibal** [comment]
I know this is a rather lengthy name but how about "Awaiting stable release"?

**Comment by Kazhnuz** [comment]
Well, as those issues won't have other labels, I think it'll work ! I'll try it.

**Comment by Kazhnuz** [comment]
Fixed by 830f2d16f6ef99b13b41116ef92aaa1334b14de1
