### ISSUE TITLE
Should we mark core apps or officially maintained packages ?

### ISSUE THREAD

**Issue by Kazhnuz** [Kazhnuz/awesome-gnome#18]
As of eafb4519628d4ba55933ece1b535e7261d497e91, we use a GNOME logo to mark application that are member of the ![Core Applications of GNOME](https://blogs.gnome.org/mcatanzaro/2016/09/21/gnome-3-22-core-apps/).

If using the set of Core Apps make it easier for us to know what item we should mark simple, the problem is that the Core Apps are just a subset of application maintained by the GNOME Project. For instance, GNOME Tweaks is maintained by GNOME, designed by the GNOME Design Team, and officially distributed as part of GNOME. But it's not a part of the GNOME Core set of applications. And even with the mention at the beginning, I think it might confuse some people to see an official part of GNOME not marked with a GNOME icon.

That's why I wonder what choice is better.

The problem with being less restructive that would be that for some items, it's a bit blurry, for instance gthumb, where it's on the GNOME git, but don't seems to be mentionned as a part of GNOME. And the problem might even grow with flatpak (as some apps like lollypops begin with org.gnome.) and the gitlab (if it's open to any apps created for the GNOME project, the frontier between a GNOME apps and a third-party apps might become even more blurry). 

A possibility would be to use the jhbuild list as a way to know what is "official", and what is mentioned as a part of GNOME in the different media (like in extensions.gnome.org)

**Comment by OriginalFannibal** [comment]
Would it be okay to close this issue as #27 offers actual guidelines on what apps to consider as core GNOME apps? You could also add the label to that issue.

**Comment by Kazhnuz** [comment]
Yes, I'm doing it now :)
