### ISSUE TITLE
Switching Licenses

### ISSUE THREAD

**Issue by OriginalFannibal** [Kazhnuz/awesome-gnome#2]
The Awesome Manifesto [recommends](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) the use of the [`CC0 1.0`](https://creativecommons.org/publicdomain/zero/1.0/) license.  

Would you be okay with its terms?

**Comment by Kazhnuz** [comment]
Yep, I'll switch that !

**Comment by Kazhnuz** [comment]
I switched the licence in the commit eeb5750ede2446615f568bca98d830fcac9d6f36 :)
