### ISSUE TITLE
Add community ressources

### ISSUE THREAD

**Issue by Kazhnuz** [Kazhnuz/awesome-gnome#28]
In the pull request to add our list to the awesome-list, Sindresorhus [mentioned that it would be good to add links to community ressources](https://github.com/sindresorhus/awesome/pull/1025#issuecomment-331972528) to the list. The community part of awesome electron have been given [as an example](https://github.com/sindresorhus/awesome-electron#community). 

So it's related to #20 

It would also help users to access more easily those community resources, as they are a bit dispersed.

**Comment by Kazhnuz** [comment]
WIP in the [community-resources](https://github.com/Kazhnuz/awesome-gnome/blob/community-resources/README.md) branch.

**Comment by OriginalFannibal** [comment]
What do you think of linking the IRC link to `irc://irc.gnome.org/gnome` instead of linking it to the list of IRC channels? `#gnome` is the channel for general discussion and help and feels like the community channel while the other channels have a more specific purpose.

**Comment by Kazhnuz** [comment]
Yeah, it's a good idea, but I think that having somewhere the list of channel could be good ? Maybe in the description ?

**Comment by OriginalFannibal** [comment]
I think that the community section looks pretty good and thorough now. Is there anything else you'd like to add before pushing it to `master`? 

Whenever you think it is ready to be pushed to `master`, do comment on [#1025](https://github.com/sindresorhus/awesome/pull/1025) that the section has been added :)

**Comment by Kazhnuz** [comment]
Yep, I was just searching if some other important place were missing. I've added the official news feed (as it's a connection between the project and the community) and the Google+ Community page.
