### ISSUE TITLE
Meta: Better categorisations for applications, extensions and themes

### ISSUE THREAD

**Issue by Kazhnuz** [Kazhnuz/awesome-gnome#3]
The current classification for applications, extensions and themes is a bit rough, and could become difficult to read when more of them will be added. Maybe we will need more categories in order to make the list easier to read for users.

Maybe it could be possible to take some inspiration from [awesome-macos](https://github.com/iCHAIT/awesome-macOS), or another awesome list of applications ?

**List of sub-issues:**
- #53 : themes

**Comment by OriginalFannibal** [comment]
Awesome macOS has a really well done system of classification and the list itself is so comprehensive. Especially like that they have even listed discussion forums. We should definitely be taking cues from them.  

Should we model our classification after theirs now or wait until we have more items to populate the list?

**Comment by Kazhnuz** [comment]
I think a solution would be for now to change where it make sense (in order to have all current applications in the new categories) and when they won't be blank, and after that add the new needed categories when we will need them as items would go inside, maybe ?

**Comment by Kazhnuz** [comment]
Created issue #53 in order to tackle the question of the categorization of theme
