### ISSUE TITLE
"extensions" is repeated in GitHub description twice

### ISSUE THREAD

**Issue by Omar-Elrefaei** [Kazhnuz/awesome-gnome#38]
![image](https://user-images.githubusercontent.com/17922991/32435019-f87fa982-c309-11e7-9702-02af7c1afe7e.png)

**Comment by Kazhnuz** [comment]
Good catch, I didn't notice it ! Thank you, I corrected it :)

**Comment by Omar-Elrefaei** [comment]
You are welcome :smiley:
