### ISSUE TITLE
Add a code-of-conduct and contributions guidelines

### ISSUE THREAD

**Issue by Kazhnuz** [Kazhnuz/awesome-gnome#4]
Contributions guidelines are a requirement to create an awesome-list, and having a code of conduct is [strongly recommended](https://github.com/sindresorhus/awesome/blob/master/create-list.md).

However, if the second part shouldn't be pretty hard (just using the awesome-list generator would be simple), the question remain for the "GNOME" parts of the contributions guidelines : How much an application here have to follow the GNOME HIG, or the common patterns of a GNOME application. For instance, having symbolic icons in the headerbar, etc.

**Comment by OriginalFannibal** [comment]
Maybe we could have a separate section for apps that don't follow the HIG but are close enough? Or would that be a cop-out?

**Comment by Kazhnuz** [comment]
I started the work in a [separate branch](https://github.com/Kazhnuz/awesome-gnome/tree/contribution-guidelines), and I started some guidelines, based on those on awesome-macos. For the moment, as it's still in construction, I think that we can wait before having the rules of making one PR for every additions (but later it might help, I think).

I'm not really sure for the separate, as I think it might make it a bit harder for an user to find the apps he want, no ? Personally, I would be more for accepting application that don't follow exactly the HIG if they have an headerbar, looks good enough and are usefull. If it suit you, I think it could be the rules...

I also wonder if we should make a rule for unmaintained apps/extensions, and thoses that haven't a release yet ?

And my last concern is about the official application. Should they be in the list or not ? And how to define if one can be in the list ? My idea would be that application that aren't part of the GNOME Core application should be in the list, but IDK for application like Epiphany, that is a Core application but isn't default in nearly any distribution.

**Comment by OriginalFannibal** [comment]
> I think that we can wait before having the rules of making one PR for every additions (but later it might help, I think).  

I agree. 

> Personally, I would be more for accepting application that don't follow exactly the HIG if they have an headerbar, looks good enough and are usefull.  

You're right. I am planning on going through the Gnome HIG thoroughly to better understand it but I do feel that we can be a little lenient if it means we can add more quality apps to the list and in a manner that would make navigating the list simple. A line needs to be drawn though.

> I also wonder if we should make a rule for unmaintained apps/extensions, and thoses that haven't a release yet ?  

I think we should definitely avoid unmaintained apps/extensions. What do you think? If we do include them then we should at least clearly label them as such. I feel the same way about pre-release software. Either avoid them or clearly label them.  
Personally, I'd prefer it if even newly released apps are allowed to mature a bit before letting them into the list. 

> And my last concern is about the official application. Should they be in the list or not ? And how to define if one can be in the list ?  

Not all of the official apps are worthy of being on the list but for the ones that are, let's include them and label them as a core Gnome app. I too would like to see them get some more attention.

**Comment by Kazhnuz** [comment]
> You're right. I am planning on going through the Gnome HIG thoroughly to better understand it but I do feel that we can be a little lenient if it means we can add more quality apps to the list and in a manner that would make navigating the list simple. A line needs to be drawn though.

Okay ! For the moment, I wrote it like that in the branch : "The application have to follow at least a bit the GNOME HIG, by using an headerbar as the titlebar and that it looks clean in a vanilla GNOME desktop."

> I think we should definitely avoid unmaintained apps/extensions. What do you think? If we do include them then we should at least clearly label them as such. I feel the same way about pre-release software. Either avoid them or clearly label them.

Personally, I'm all for avoiding them. The only exception that I would see would be for essential application without any alternative.
I agree with you for the newly released app.

I worded it this way : "Please avoid unmaintained applications or extensions, as they could break with time. Please also avoid application that haven't any stable release yet or that aren't mature yet."

> Not all of the official apps are worthy of being on the list but for the ones that are, let's include them and label them as a core Gnome app. I too would like to see them get some more attention.

I agree with you, and labeling as core GNOME apps is a good idea !

**Comment by Kazhnuz** [comment]
Fixed with #7. Problems with the contributions guidelines and the CoC will be fixable in separate issues and PR :)
