### ISSUE TITLE
Add uberwriter

### ISSUE THREAD

**Issue by dyskette** [Kazhnuz/awesome-gnome#54]
Although I don't know in which section. UberWriter is a markdown editor and you can check it out in https://github.com/UberWriter/uberwriter

It's also available in flathub now, so it's easy to try it.

**Comment by Kazhnuz** [comment]
Thank you, I didn't see much the new work on Uberwriter ! I'll create an "editor" category for this application and other text editor for GNOME (a bit like in the awesome-macos list).
