### ISSUE TITLE
Easy eBook Viewer is unmaintained

### ISSUE THREAD

**Issue by johnfactotum** [Kazhnuz/awesome-gnome#64]
Easy eBook Viewer is unmaintained; has been since [a year ago](https://github.com/michaldaniel/ebook-viewer/commit/5a0aa93f50ae28704bf714fff145aff645605690).

There seems to be *one* updated fork at [joeriexelmans/ebook-viewer](https://github.com/joeriexelmans/ebook-viewer).

Also the name should probably be "Easy eBook Viewer" (as defined in the application and its .desktop file) and not "Easy Ebook Viewer".

**Comment by Kazhnuz** [comment]
I'll put for the moment the updated fork instead of the old mainstream. Thanks for the information !

Good point on that second aspect.
