### ISSUE TITLE
Add Firefox GNOME theme

### ISSUE THREAD

**Issue by johnfactotum** [Kazhnuz/awesome-gnome#65]
https://github.com/rafaelmardojai/firefox-gnome-theme

Not sure which category it would fit in, but it's a great theme with a lot of attention to details, and it really enhances the Firefox experience on GNOME tremendously.

**Comment by Kazhnuz** [comment]
This project is totally in the scope of the list ! As for the category, I think that kind of stuff could deserve a whole category just for them, but I'm not sure of the name. Third-party integration ? External Software Integration ? I'll work on that, thanks :)
