### ISSUE TITLE
Add Foliate

### ISSUE THREAD

**Issue by Nilsolm** [Kazhnuz/awesome-gnome#66]
[Foliate](https://github.com/johnfactotum/foliate) is a relatively new ePub reader built with GTK. It seems to be under very active development but I see no indication that it is considered to be unstable, so I think it fits.

**Comment by Kazhnuz** [comment]
You are right, it seems to be stable, and even if the developpement is still active, it already have stable versions ! (as the last version is 1.4.0). I'll add it ! Thanks !
