### ISSUE TITLE
Add Lutris when lutris-next branch is released

### ISSUE THREAD

**Issue by dyskette** [Kazhnuz/awesome-gnome#9]
Lutris has a branch in git called lutris-next where it uses GtkHeaderbar for the application window.

https://github.com/lutris/lutris/blob/next/share/lutris/ui/lutris-window.ui#L25

Given the development pace it could take a while though.

**Comment by Kazhnuz** [comment]
Nice, I'll keep a look on it until it's merged :) Thank you !
