### ISSUE TITLE
Indicate Circle apps and librairies

### ISSUE THREAD

**Issue by Kazhnuz** [Kazhnuz/awesome-gnome#96]
The GNOME Circle project is a project kinda similar to awesome gnome, in that it aim to show quality third party GNOME Apps. Indicating Circle Apps could be great, as it's an interesting information for the user, which apps have been accepted into GNOME Circle.

**Comment by BrainBlasted** [comment]
Perhaps these branding resources can help? https://gitlab.gnome.org/Teams/Design/brand/-/blob/master/subbrands/gnome-circle/gnome-circle.png

**Comment by BrainBlasted** [comment]
A symbolic exported as PNG: ![circle-symbolic](https://user-images.githubusercontent.com/29347290/97769964-612ee780-1aec-11eb-808c-dad52ced9cf6.png)

**Comment by Kazhnuz** [comment]
Oh, thank you very much for the exported symbolics ! Yes, this will help !

Really sorry for not having answered sooner, I thought I had answered and I haven't been quite active the few last day x.x'
